### ISSUE TITLE
Please add build results also

### ISSUE THREAD

**Issue by vettukal** [karino2/rmatesync#4]
Hi can you add build files somewhere in /bin folder

>     RMateSync.exe
>     LiteDB.dll
>     settings.ini

I dont have VS. This will help tremendously.

**Comment by karino2** [comment]
Thank you for your interested.
I add binary as RMate.zip.

(https://github.com/karino2/rmatesync/commit/24b9dd1d1b736a13d07d203912de28fe1829cc2d)
